[env]
EDITOR = "nvim"

[tools]
go = "latest"
lua = "latest"
lua-language-server = "latest"
ninja = "latest"
node = "latest"
ruby = "latest"
stylua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
